"""Contingency table, sample counts, assumptions text, and modelling
statements (results-page features 5, 8, 10). Static prose is ported
verbatim from the old site's `result_show.html`; the per-estimand
"extra assumptions" are DoWhy's own auto-generated text (see
identification.py) - nothing custom to reverse-engineer there.
"""

from __future__ import annotations

import pandas as pd

SITE_URL = "https://causalwizard.app"

GENERAL_ASSUMPTIONS = [
    ("Data represents an unbiased sample",
     "The data used for this study should be an unbiased and representative sample of the population you want to draw conclusions about."),
    ("Domain knowledge is correctly captured",
     "The causal diagram (or panel-data structure) should correctly and completely capture the relevant domain knowledge - missing or incorrect relationships will bias the result."),
    ("The model is appropriate",
     "The chosen estimation method should be a reasonable fit for the data and the question being asked - check the validation tests above."),
    ("The sample is sufficiently large",
     "Causal estimates, like all statistics, are more reliable with more data. Small samples produce noisy, unreliable estimates even when every other assumption holds."),
]

CDPO_ASSUMPTIONS = [
    ("Positivity", "Every unit must have a nonzero probability of receiving either treatment level, given its covariates - see the positivity check above, if shown."),
    ("Consistency", "The observed outcome for a treated (or control) unit equals its potential outcome under the treatment (or control) it actually received."),
    ("Ignorability / Exchangeability", "Conditional on the observed covariates, treatment assignment is independent of the potential outcomes - i.e. no unmeasured confounding."),
    ("No Unmeasured Confounding", "There are no unobserved common causes of treatment and outcome not already captured by the causal diagram."),
    ("SUTVA", "The Stable Unit Treatment Value Assumption: one unit's outcome doesn't depend on another unit's treatment assignment, and there's only one version of each treatment level."),
]

PDFE_ASSUMPTIONS = [
    ("Time-invariant Unobserved Heterogeneity", "Unobserved confounders may exist, as long as they don't change over time within an entity - fixed effects absorb these."),
    ("Strict Exogeneity", "The treatment (and covariates) in any time period are uncorrelated with the error term in every time period, past and future."),
    ("No Perfect Collinearity", "No covariate is a constant, or an exact linear function of the other covariates, entity effects, or time effects."),
    ("Homoscedasticity / Independence of Errors", "Handled here via cluster-robust standard errors, which don't require errors to have constant variance."),
    ("No Serial Correlation", "Also handled via entity-clustered standard errors, which allow for arbitrary correlation between observations of the same entity over time."),
    ("Common Time Trends", "Time fixed effects assume that time-varying shocks affect every entity equally."),
    ("Parallel Trends (if comparing groups over time)", "Absent treatment, treated and control entities would have followed the same trend over time."),
    ("No Spillover", "One entity's treatment doesn't affect another entity's outcome."),
]


def assumptions_markdown(method: str, dowhy_assumptions: dict | None) -> str:
    method_label = "Potential Outcomes" if method == "cd+po" else "Panel Data / Fixed-Effects"
    method_assumptions = CDPO_ASSUMPTIONS if method == "cd+po" else PDFE_ASSUMPTIONS
    lines = [
        f"The validity of the findings above depends on these assumptions holding "
        f"([read more]({SITE_URL}/articles/assumptions/)).",
        "",
        "**General:**",
        "",
    ]
    lines += [f"- **{title}:** {text}" for title, text in GENERAL_ASSUMPTIONS]
    lines += ["", f"**{method_label} method:**", ""]
    lines += [f"- **{title}:** {text}" for title, text in method_assumptions]
    if dowhy_assumptions:
        lines += ["", "**Specific to this estimand (generated by DoWhy from your causal diagram):**", ""]
        lines += [f"- **{title}:** {text}" for title, text in dowhy_assumptions.items()]
    return "\n".join(lines)


def contingency_table(df: pd.DataFrame, treatment_col: str, outcome_col: str, outcome_is_categorical: bool, class1_label: str | None) -> dict:
    control = df[df[treatment_col] == 0]
    treated = df[df[treatment_col] == 1]
    result: dict = {
        "total": {"control": int(len(control)), "treated": int(len(treated)), "total": int(len(df))},
    }
    if outcome_is_categorical:
        result["by_outcome"] = {
            "0": {"control": int((control[outcome_col] == 0).sum()), "treated": int((treated[outcome_col] == 0).sum())},
            "1": {"control": int((control[outcome_col] == 1).sum()), "treated": int((treated[outcome_col] == 1).sum())},
        }
        result["class1_label"] = class1_label
    return result


ACCEPT_TEXT = (
    "All validation tests passed. The validation tests explore the robustness and stability of the "
    "results. This provides confidence in the estimated causal effect, as long as no assumptions are "
    "violated."
)

REJECT_TEXT = (
    "Some validation tests failed. This means the estimate of the causal effect should be treated "
    "cautiously. Examine the validation tests to understand whether the model was close to passing, "
    "or failed by a large margin. Validation failure means the true effect might be zero, even if the "
    "current estimate is large. Also, if the current estimate is close to zero, it does not confirm "
    "the absence of a causal effect - a significant effect might still be found with more data, or "
    "other settings."
)


def findings_statement(
    treatment_col: str,
    outcome_col: str,
    treatment_is_continuous: bool,
    outcome_effective_type: str,
    outcome_class1_label: str | None,
    target_units: str,
    effect: float,
) -> str:
    """The plain-English "what does this effect mean" sentence (results-page
    feature 1) - ported from result.js's setFindingsEffect(), same wording
    and same branching (binary vs continuous treatment design x categorical
    vs numerical outcome x ATE/ATT/ATC), minus the HTML/jQuery plumbing."""
    sign = "increased" if effect >= 0 else "decreased"
    magnitude = effect if outcome_effective_type == "categorical" else abs(effect)

    if outcome_effective_type == "categorical":
        outcome_phrase = f"the probability {outcome_col} = 1 ({outcome_class1_label})"
    else:
        outcome_phrase = f"the value of outcome {outcome_col}"

    subgroup = {
        "ate": ".",
        "att": ", for samples which were originally in the Treated group.",
        "atc": ", for samples which were originally in the Control group.",
    }[target_units]

    if treatment_is_continuous:
        return (
            f"This means that {outcome_phrase} is on average {sign} by {magnitude:.4g} "
            f"for every unit change in {treatment_col}{subgroup}"
        )
    return (
        f"This means that when treatment {treatment_col} = Treated, {outcome_phrase} is on average "
        f"{sign} by {magnitude:.4g} compared to when {treatment_col} = Control{subgroup}"
    )


TARGET_UNIT_LABELS = {
    "ate": "Average Treatment Effect (ATE)",
    "att": "Average Treatment effect on the Treated (ATT)",
    "atc": "Average Treatment effect on the Controls (ATC)",
}


def findings_markdown(
    treatment_col: str,
    outcome_col: str,
    treatment_is_continuous: bool,
    outcome_effective_type: str,
    outcome_class1_label: str | None,
    target_units: str,
    effect: float,
    accept: bool | None,
) -> str:
    """The headline result, as Markdown - the effect number is the single
    most important figure in the whole report, so it gets a heading of its
    own rather than being just another line of plain text among many."""
    statement = findings_statement(
        treatment_col, outcome_col, treatment_is_continuous, outcome_effective_type,
        outcome_class1_label, target_units, effect,
    )
    if accept is None:
        verdict = "_No validation tests were run for this estimator - see the Validation section below._"
    elif accept:
        verdict = f"**Validation: passed.** {ACCEPT_TEXT}"
    else:
        verdict = f"**Validation: some tests failed.** {REJECT_TEXT}"
    label = TARGET_UNIT_LABELS[target_units]
    return (
        f"### {label}: {effect:.4g}\n\n"
        f"The effect of treatment **{treatment_col}** on outcome **{outcome_col}** was estimated as "
        f"**{effect:.4g}**.\n\n"
        f"{statement}\n\n"
        f"> {verdict}"
    )


def modelling_statements(
    method: str,
    treatment_col: str,
    outcome_col: str,
    treatment_is_continuous: bool,
    outcome_effective_type: str,
    outcome_class1_label: str | None,
    sample_counts: dict,
    estimand_type: str | None,
    estimand_expression: str | None,
    estimator_name: str,
    panel_data: dict | None,
) -> dict:
    return {
        "methodology": "Causal Diagram and Potential Outcomes framework." if method == "cd+po" else "Fixed-effects model applied to Panel Data.",
        "study_design": "Continuous, numerical treatment." if treatment_is_continuous else "Binary treatment (comparison of Control and Treated groups).",
        "treatment_variable": treatment_col,
        "outcome_variable": outcome_col,
        "outcome_type": (
            f"Categorical: 0 vs 1 ({outcome_class1_label})" if outcome_effective_type == "categorical" else "Numerical (Integer or Real)"
        ),
        "sample_counts": sample_counts,
        "panel_data": panel_data,
        "estimand_type": estimand_type,
        "estimand_expression": estimand_expression,
        "estimator_name": estimator_name,
    }


STATEMENT_LABELS = {
    "methodology": "Methodology",
    "study_design": "Study design",
    "treatment_variable": "Treatment variable",
    "outcome_variable": "Outcome variable",
    "outcome_type": "Outcome type",
    "sample_counts": "Sample counts",
    "panel_data": "Panel data",
    "estimand_type": "Estimand type",
    "estimand_expression": "Estimand expression",
    "estimator_name": "Estimator",
}


def modelling_statements_markdown(stmts: dict) -> str:
    """modelling_statements()'s dict as a Markdown bullet list, for
    display(Markdown(...)) - notebook 2 shows this up top rather than as a
    plain dict dump at the bottom."""
    lines = []
    for key, label in STATEMENT_LABELS.items():
        value = stmts.get(key)
        if value is None:
            continue
        lines.append(f"- **{label}:** {value}")
    return "\n".join(lines)


def generalization_unavailable_reason(method: str, estimator: str | None) -> str | None:
    """Why the held-out generalization check isn't shown for this
    estimator, or None if it is. PD+FE and CD+PO's own linear
    regression/GLM always have a real fitted "predict Y from X" model, so
    they're always eligible."""
    if method == "pd+fe" or estimator in ("linear_regression", "generalized_linear_model"):
        return None
    if estimator == "econml.dml.DML":
        return (
            "Double ML's do-operator only gives the shift from a row's actual treatment to a "
            "counterfactual one (used for the counterfactual table above) - its \"prediction\" for "
            "a row's actual treatment is just that row's own observed outcome, so a held-out "
            "accuracy check would trivially show a perfect fit. Not shown for that reason."
        )
    if estimator in ("propensity_score_weighting", "propensity_score_matching", "propensity_score_stratification"):
        return (
            "Propensity-based estimators compare treated and control groups directly (via "
            "weighting/matching/stratification) rather than fitting a model that predicts a row's "
            "outcome from its covariates, so there's no outcome model to check against held-out data."
        )
    return "This estimator doesn't fit a model that predicts a row's outcome from its covariates."


VALIDATION_LABELS = {
    "bootstrap": "Bootstrap significance",
    "placebo_treatment": "Placebo treatment refuter",
    "random_common_cause": "Random common cause refuter",
    "z_statistic": "Treatment coefficient z-statistic",
    "f_statistic": "Overall model F-statistic",
}


# {key: (description, desired result, is "Significant"=True the good outcome?)}
# - ported from result_show.html's validation table, one row per test.
# The third element is the non-obvious part: bootstrap (and PD+FE's z/F
# tests) follow the intuitive convention where Significant=True supports
# the effect being real, but the two refuters are backwards - they
# deliberately try to make the effect disappear (placebo) or stay
# unaffected (random common cause), so finding a *significant* result
# there means the refuter caught a problem. See
# bootstrap-refuters-dowhy for the full derivation of both conventions.
VALIDATION_DESCRIPTIONS = {
    "z_statistic": (
        "Tests the significance of the treatment variable's own coefficient. The p-value is the "
        "probability of a z-statistic this extreme under the null hypothesis that treatment has no "
        f"effect ([read more]({SITE_URL}/articles/z-statistic/)).",
        "p ≤ 0.05", True,
    ),
    "f_statistic": (
        "Tests the overall significance of the regression model - whether *at least one* input "
        f"variable has a non-zero coefficient ([read more]({SITE_URL}/articles/f-statistic/)).",
        "p ≤ 0.05", True,
    ),
    "bootstrap": (
        "Randomly permutes the outcome many times, destroying any real causal effect, and measures "
        "how often a result this strong appears by chance alone "
        f"([read more]({SITE_URL}/articles/random-outcomes/)).",
        "p ≤ 0.05", True,
    ),
    "placebo_treatment": (
        "Randomly permutes the treatment, destroying any real causal effect, and re-estimates - a "
        "robust result should see the effect collapse towards zero "
        f"([read more]({SITE_URL}/articles/placebo-treatment/)).",
        "New effect ≈ 0", False,
    ),
    "random_common_cause": (
        "Adds an extra, random, independent variable as if it were a confounder and re-estimates - a "
        "robust result shouldn't move much "
        f"([read more]({SITE_URL}/articles/random-common-cause/)).",
        "Effect unchanged", False,
    ),
}


def validation_rows(validation: dict | None) -> list[dict]:
    """validation dict (CD+PO's bootstrap/placebo/random-common-cause, or
    PD+FE's z/f-statistic) as one row per test that's actually present -
    a uniform table shape regardless of method, for display(pd.DataFrame(...))
    rather than a raw dict dump that's easy to skim past.

    "Estimate valid?" is the test's raw Significant flag translated
    through VALIDATION_DESCRIPTIONS' good/bad direction into the actual
    question a reader cares about - Yes/No, not "Significant: True/False"
    that means the opposite thing for two of the five tests."""
    if not validation:
        return []
    rows = []
    for key, label in VALIDATION_LABELS.items():
        if key not in validation:
            continue
        v = validation[key]
        significant = v.get("significant")
        significant_is_good = VALIDATION_DESCRIPTIONS[key][2]
        valid = (significant if significant_is_good else not significant) if significant is not None else None
        row = {
            "Test": label,
            "p-value": v.get("p_value"),
            "Significant": significant,
            "Estimate valid?": {True: "Yes", False: "No", None: ""}[valid],
        }
        if "new_effect" in v:
            row["New effect"] = v["new_effect"]
        if "confidence_interval" in v:
            row["95% CI"] = v["confidence_interval"]
        rows.append(row)
    return rows


def validation_markdown_intro(validation: dict | None) -> str:
    if not validation:
        return "_No validation tests were run for this estimator._"
    lines = [
        "Several tests were applied to assess the statistical significance, robustness and stability "
        "of the result. **\"Significant\" doesn't always mean \"good\" here** - the bootstrap "
        "significance test (and PD+FE's z/F-statistics) follow the usual convention where "
        "Significant = True supports the effect being real, but the two refuters below are "
        "deliberately built to try to make the effect disappear (placebo treatment) or stay "
        "unaffected (random common cause) - so for *those two*, Significant = True means the "
        "refuter found a problem, not that it confirmed one "
        f"([read more]({SITE_URL}/articles/bootstrap-refuters-dowhy/)):",
        "",
    ]
    for key, label in VALIDATION_LABELS.items():
        if key not in validation:
            continue
        desc, desired, significant_is_good = VALIDATION_DESCRIPTIONS[key]
        verdict = "Significant = **good**" if significant_is_good else "Significant = **bad**, not significant is good here"
        lines.append(f"- **{label}** (desired: {desired}; {verdict}) - {desc}")
    return "\n".join(lines)


def generalization_markdown_intro(n_test: int) -> str:
    return (
        f"Can the model predict outcomes it wasn't fit on? It was evaluated against a **held-out test "
        f"set of {n_test} samples**, not available to it during training. This is a check that the "
        "model is capturing real structure in your data rather than just fitting noise - good "
        "performance here gives extra confidence in the result, and poor performance means every other "
        "result on this page (which all depend on the model's ability to predict outcomes) should be "
        "treated cautiously.\n\n"
        "_Note: a score that looks suspiciously good (e.g. R² ≥ 0.98) may indicate data leakage "
        "rather than a great model - double check the treatment/outcome variables aren't accidentally "
        "encoding each other._"
    )


NUMERICAL_METRIC_NOTES = [
    ("R² (coefficient of determination)", "The proportion of variance in the outcome explained by the model - 0 to 1, higher is better."),
    ("RMSE (root mean squared error)", "Typical prediction error size, in the outcome's original units."),
    ("MAE (mean absolute error)", "Average absolute prediction error, in the outcome's original units - less sensitive to a few large errors than RMSE."),
]

CATEGORICAL_METRIC_NOTES = [
    ("Accuracy", "The percentage of outcomes correctly predicted - can be misleading with imbalanced classes."),
    ("F1-score", "Balances precision and recall into one number (1 is ideal) - usually more informative than accuracy when classes are imbalanced."),
    ("Precision", "Of the samples predicted class 1, the percentage that actually were class 1."),
    ("Recall", "Of the samples actually class 1, the percentage predicted as class 1."),
]


def generalization_metric_notes_markdown(outcome_is_binary: bool) -> str:
    notes = CATEGORICAL_METRIC_NOTES if outcome_is_binary else NUMERICAL_METRIC_NOTES
    return "\n".join(f"- **{k}:** {v}" for k, v in notes) + f"\n\n[Read more]({SITE_URL}/articles/metrics/) about these metrics."


def generalization_plot_markdown() -> str:
    return (
        "Predicted values are plotted against actual values for the held-out test samples. A perfect "
        "model would put every point on the dashed diagonal; divergence from it is error. The red trend "
        "line shows the model's overall response - ideally rising left-to-right. Control and treated "
        "samples are shown separately, so you can spot whether the model is worse for one group."
    )


def counterfactual_markdown_intro(
    treatment_is_continuous: bool, outcome_is_binary: bool, control_value: float, treated_value: float,
    available: bool,
) -> str:
    lines = [
        "For a fixed treatment value, every row's treatment is set to that value and the outcome is "
        "predicted (the \"do-operator\"). This table summarizes those predictions under several "
        "scenarios: the actual data as observed, and hypothetical ones like \"if every sample had been "
        "treated\"."
    ]
    if not available:
        lines.append(
            "\n_Not available for this estimator - only ones with a do-operator (own linear "
            "regression/GLM, Double ML, or PD+FE) support this._"
        )
        return "\n".join(lines)
    if outcome_is_binary:
        lines.append(
            "\nSince the outcome is categorical, \"Sum\" is the predicted **count** of class-1 outcomes "
            "and \"Mean\" is the predicted **probability** of class 1 - not a separate per-category tally."
        )
    if treatment_is_continuous:
        lines.append(
            f"\nSince the treatment is continuous, counterfactual outcomes are evaluated at two fixed "
            f"values: **Lower (Control) = {control_value}** and **Upper (Treated) = {treated_value}**."
        )
    return "\n".join(lines)


def contingency_markdown_intro() -> str:
    return (
        "Check the number of samples in each treatment/outcome group. Samples are sometimes "
        "unexpectedly lost to missing values, or you might be looking at the wrong data file. Also "
        "check the Control/Treated split isn't too skewed, and that every categorical outcome value is "
        "reasonably common."
    )


def positivity_markdown_intro() -> str:
    return (
        "A causal estimate is only valid if the data contains examples of *both* treatment levels "
        f"across the full range of covariate combinations - the **positivity** assumption "
        f"([read more]({SITE_URL}/articles/positivity/)). This is checked by comparing the distribution "
        "of propensity scores between the Control and Treated groups below: they should cover a similar "
        "range, with neither group having many samples at the extremes (close to 0 or 1). Values beyond "
        "the dashed red lines are in the unreliable tail and, if numerous, should be investigated or "
        "excluded."
    )


def covariate_balance_markdown_intro() -> str:
    return (
        "Propensity weighting/matching aims to make the Control and Treated groups statistically "
        f"similar on every covariate - **covariate balance** ([read more]({SITE_URL}/articles/covariate-balance/)). "
        "The plot below (a \"Love plot\") shows the absolute standardized mean difference (SMD) between "
        "groups for each covariate, before and after weighting - a categorical covariate gets one row per "
        "value (e.g. \"region = North\"), each treated as its own 0/1 indicator. Balance is considered "
        "good when the weighted SMD is close to zero; 0.1 is a common threshold, shown as a dashed line, "
        "but it's indicative rather than a hard cutoff."
    )


def regression_summary_markdown_intro() -> str:
    return (
        "The full model fit, straight from statsmodels - includes overall fit statistics (R², "
        "F-statistic) and a coefficient for every input feature (covariates plus treatment). The "
        "**sign** of a coefficient tells you the direction of association and the **magnitude** how "
        "strongly the model weighs that feature - check both against your own expectations as a sanity "
        "check. Coefficients close to zero are unstable and best ignored; if your numerical variables "
        "aren't on comparable scales, don't directly compare magnitudes across them "
        f"([read more]({SITE_URL}/articles/feature-importance/))."
    )


def causal_diagram_markdown_intro() -> str:
    return (
        "The graph below is the causal diagram you provided as prior domain knowledge - the validity of "
        "the estimated effect depends on this graph being a correct and complete description of the "
        "relationships between your variables."
    )
